#!/bin/bash

mkdir -p assets
GOOS=linux GOARCH=amd64 go build -o assets/in in/main.go
GOOS=linux GOARCH=amd64 go build -o assets/out out/main.go
GOOS=linux GOARCH=amd64 go build -o assets/check check/main.go
