#!/bin/bash

set -e

not_installed() {
  ! command -v $1 > /dev/null 2>&1
}

semver_resource_dir=$(cd $(dirname $0)/.. && pwd)

if not_installed ginkgo; then
  echo "# ginkgo is not installed! run the following command:"
  echo "    go install github.com/onsi/ginkgo/ginkgo"
  exit 1
fi

if not_installed docker; then
  echo "# docker is not installed! run the following commands:"
  echo "    brew install docker"
  exit 1
fi

if not_installed docker-machine; then
  echo "# docker-machine is not installed! run the following commands:"
  echo "    brew cask install docker-machine"
  exit 1
fi

cd $semver_resource_dir
ginkgo -r -p version

./scripts/build
set +e
docker build .
if [ "$?" != "0" ] ; then
  set -e
  echo "# make sure you have run the following commands:"
  echo "    docker-machine create dev --driver virtualbox"
  echo '    eval $(docker-machine env dev)'
  echo "    docker login"
  exit 1
fi
set -e
