#!/bin/bash
# vim: set ft=sh

set -e

export GOROOT=/usr/src/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd $GOPATH/src/github.com/concourse/semver-resource

export GOPATH=${PWD}/Godeps/_workspace:$GOPATH
export PATH=${PWD}/Godeps/_workspace/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -p "$@"

go build -o built-in in/main.go
go build -o built-out out/main.go
go build -o built-check check/main.go
